fieldLayouts:
  c501c220-0a3a-4190-9a35-01cc6e6524d7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 59f21590-4092-4357-9d07-584db04b94af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 365e6f9b-d7e6-4842-9949-cbcb3f3add5c # Galeriebild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca1492af-5f9c-426a-8e6e-d9b769ad320c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d974c4b2-0f74-46a2-8ff3-8e2df02ab3d6 # Bilder pro Seite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06ff275e-b48a-4cb5-941a-5f9c5656c5bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54ca8698-f1ca-4e92-bb88-da59db94c132 # Download erlauben
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35b4ebcc-9c02-4a6e-ba3c-c605a23ca89c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3c8fa34-6148-455b-9606-0750a8a222e6 # Bilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 905562a1-1ae1-4195-bfbc-df316e2c3f36
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: dd50bb2f-55dc-4af4-939e-c143eca5c074
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 91089a32-9653-4514-98e8-030bfdcfc062 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72cee915-4fbb-4d46-a1b2-fedd07995ae8
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 33ef616b-7365-4827-a2ca-67429b0a9616
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: 535ca493-eede-4a95-abc7-46ece09cff7e # Galerien
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
