fieldLayouts:
  a0574711-6e73-4875-8e3d-ae086b9a9d78:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fc0bbeac-0eda-401d-b321-0fe1a09589f6
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 04876dd4-ef6d-46a1-b96f-16a3864a27f6
        userCondition: null
fs: visuales
handle: keyvisuales
name: Keyvisuales
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
