columnSuffix: null
contentColumnType: string
fieldGroup: 939a2d54-9b3c-4e76-8353-32f820e7c737 # Common
handle: keyvisual
instructions: null
name: Keyvisual
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:11a33489-81b7-4623-9d2c-4a06045e0a66' # Keyvisuales
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:11a33489-81b7-4623-9d2c-4a06045e0a66' # Keyvisuales
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:11a33489-81b7-4623-9d2c-4a06045e0a66' # Keyvisuales
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
