defaultPlacement: end
enableVersioning: true
handle: galleries
name: Galerien
propagationMethod: all
siteSettings:
  6cb45d1b-95aa-466e-b450-eeca6d207e1f: # WIRO Intercup 2024
    enabledByDefault: true
    hasUrls: true
    template: _gallery/index.twig
    uriFormat: 'galerien/{slug}'
structure:
  maxLevels: 1
  uid: 85a802c1-1855-4177-8bcf-c9a6b9c5c671
type: structure
