defaultPlacement: end
enableVersioning: true
handle: startseite
name: Startseite
propagationMethod: all
siteSettings:
  6cb45d1b-95aa-466e-b450-eeca6d207e1f: # wiro-bilder
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
